### PR TITLE
Fix duplicated frame in crossfade

### PR DESCRIPTION
**Pull request by dnjulek**
Crossfade repeats the last frame.

### CODE REVIEW

**Comment by kageru** [comment]
Are you sure? With your change, fading two clips of 100 frames each over a fade duration of 50 frames produces 149 frames in total instead of the 150 I’d expect.
The faded area stops at `clipb[:duration]` which does *not* include `clipb[duration]`, so I don’t see where we’re duplicating a frame here.

**Comment by dnjulek** [comment]
This way the output gets an extra frame:
``fade = crossfade(src[:667], src[641:], 667-641-1)``

If I do it this way the frame number is the same as the input, but this makes ghost in motion frames:
``fade = crossfade(src[:667], src[641:], 667-641)``

Sure, if the fade is made to a black clip it won't generate a ghost, but if it's the same scene it creates the ghost.

**Comment by SebaztianMC** [comment]
Bro, a question, about the kagegunc, the truth is I don't know how to use it, and I read your decumentacion about the function, but I don't understand it, so I would like to see if I can contact you to help me to use it. :c

**Comment by kageru** [comment]
> Sure, if the fade is made to a black clip it won't generate a ghost, but if it's the same scene it creates the ghost.

What exactly do you mean by ghosting here that isn’t expected behavior when fading a clip into itself? Could you provide an example, ideally an image of the affected frame?

**Comment by SebaztianMC** [comment]
Nono bro, when I said I didn't understand about kagefunc I mean everything, how to apply it, what does it do, its before and after applying it with image if possible, I also read in your blog, but I also didn't understand why you wrote that huge command etc, so I would like you to help me on that, how do I talk to you?

**Comment by kageru** [comment]
> Nono bro, when I said I didn't understand about kagefunc I mean everything, how to apply it, what does it do, its before and after applying it with image if possible, I also read in your blog, but I also didn't understand why you wrote that huge command etc, so I would like you to help me on that, how do I talk to you?

I wasn’t talking to you. Stop abusing other people’s PRs as support chats. Read the docs at http://vapoursynth.com/doc/; they should answer most questions.

**Comment by dnjulek** [comment]
I don't know if I am doing something wrong, but here is an example:
Considering this clip with 40 frames:
https://cdn.discordapp.com/attachments/434139618959556647/816081667693084752/test.mkv
If I add some heavy filter on it (grain in this example), and want to make a fade like this.

``` py
src = core.ffms2.Source(r"D:\test.mkv")
grn = core.grain.Add(src, 10)

src_b = src.text.FrameNum(7)[:31]
grn_b = grn.text.FrameNum(9)[10:]

fade = crossfade(src_b, grn_b, 20).set_output()
```
Frame 29 gets duplicated and the output goes from 40 frames to 41 frames.
If I change the fate duration from 20 to 21 the output is correct, but all frames get ghosted.

**Comment by SebaztianMC** [comment]
Indeed kageru, but regarding the kagefunc it takes me to your github, so I would like you to explain it better to understand it better.

**Pull request closed without merging**
